### ISSUE TITLE
JavaScript Group Capstone Project Setup

### ISSUE THREAD

**Issue by ikennarichard** [MussieTeka/JavaScript-Group-Capstone#21]
Hello,

As we begin working on our JavaScript Capstone project, we need to set up our project environment. To begin, please find the link to our project repository: https://github.com/MussieTeka/JavaScript-Group-Capstone. As a reminder, our team comprises the following members:

Student A: @MussieTeka 
Student B: @ikennarichard
 
We are using this issue to outline our initial setup steps. 

Best.

**Comment by Qoosim** [comment]
#  *Status: Required Changes* :recycle:

Hi @team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  Kanban board set up properly. :heavy_check_mark: 
-  Tasks shared between the group fairly. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

- [ ] It is required In the copied template used that every task assigned to an assignee should have the avatar of the assignee on the ticket. There's  not avatar of assignees on all the tickets on your kanban board. Kindly look into that and fix.

### Your Kanban board
![your-kanban-board](https://user-images.githubusercontent.com/26597432/232443453-5265ab0b-beb0-4f7b-abb8-3da157f2d87e.png)

### Template 
![temp-kanban-board](https://user-images.githubusercontent.com/26597432/232443484-79dce38d-9223-4c9f-936b-14742789c77d.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MussieTeka** [comment]
Thank you for your feedback @Qoosim, We have successfully assigned team members to each task, and the profile picture of each member should be shown as an avatar with each respective task.

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @MussieTeka and @ikennarichard,

✔️ Tasks are properly assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
